version: '3'
services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_SHEET_JSON=${GOOGLE_SHEET_JSON}
      - SPREAD_SHEET_ID=${SPREAD_SHEET_ID}
      - JWT_KEY=${JWT_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PWD=${REDIS_PWD}