spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PWD}


server:
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml # mapper 경로 설정
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hk_music_cop.demo.**.domain, com.hk_music_cop.demo.**.dto # 도메인 폴더 설정

jwt:
  secret: ${JWT_KEY}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-days: 14

jandi:
  color:
    success-color: '#68BB6C'
    fail-color: '#FF6188'
  title:
    info-title: '내 정보 조회'
    week-schedule-title: '주 일정 조회'
    day-schedule-title: '일 일정 조회'
    lottery-title: '추첨 결과'
    success-title: 'SUCCESS'
    fail-title: 'FAIL'

#  구글시트 설정
#  월요일 시작 알파벳 C 끝나는 알파벳 G
#  1주차부터 10, 12, 14, 16, 18
google-sheet:
  spreadsheet_id: ${SPREAD_SHEET_ID}
  calendar:
    day-list: [월,화,수,목,금]
    day-code: [C,D,E,F,G]
    sheet-numbers: [10,12,14,16,18]
  config:
    key: ${GOOGLE_SHEET_JSON}
    serviceName: '일정관리 시스템'

